# Site settings
title: Dependency Injection
email: paul@hammant.org
description: > # this means to ignore newlines until "baseurl:"
  What is and what is not Dependency Injection
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dependency.in" # the base hostname & protocol for your site
twitter_username: paul_hammant
github_username:  paul-hammant/di

# Build settings
markdown: kramdown
